name: Build

on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ 'master' ]

  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update Router List
        if: (github.event_name == 'schedule' || github.event_name == 'workflow_dispatch')  && github.ref == 'refs/heads/master'
        run: |
          sh ./ClashX/rule_providers/ad_block/gen_ad_block_list.sh ./ClashX/rule_providers/ad_block/
          sh ./Script/gen_clash_anycast_list.sh > ClashX/rule_providers/anycast.yaml
          sh ./Script/gen_cloudfront_list.sh > ClashX/rule_providers/cloudfront.yaml
          sh ./Script/gen_quantmultx_anycast_list.sh > QuantmultX/Filter/Anycast.list
          sh ./Script/gen_china_asn_router_list.sh > QuantmultX/Filter/China_ASN_router.list

      - name: Update AS IP Range List
        if: (github.event_name == 'schedule' || github.event_name == 'workflow_dispatch')  && github.ref == 'refs/heads/master'
        run: |
          sh ./ClashX/rule_providers/as_ip_range/AS8075/gen_as714.sh > ./ClashX/rule_providers/as_ip_range/AS714/as714_ipcidr.yaml
          sh ./ClashX/rule_providers/as_ip_range/AS8075/gen_as8075.sh > ./ClashX/rule_providers/as_ip_range/AS8075/as8075_ipcidr.yaml
          
          
      - name: Commit update
        if: (github.event_name == 'schedule' || github.event_name == 'workflow_dispatch')  && github.ref == 'refs/heads/master'
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          if [[ -n $(git status --porcelain) ]]; then
            git add .
            git commit -m "update $(date +%Y-%m-%d)"
            git push -q
          else 
            echo "No changes to commit."
          fi
          
          