name: Build

on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ 'master' ]

  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update Router List
        if: (github.event_name == 'schedule' || github.event_name == 'workflow_dispatch')  && github.ref == 'refs/heads/master'
        run: |
          sh ./Script/gen_anycast_list.sh > QuantmultX/Filter/Anycast.list
          sh ./Script/gen_china_asn_router_list.sh > QuantmultX/Filter/China_ASN_router.list
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "update $(date +%Y-%m-%d)"
          git push -q